#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE synthea;
    CREATE DATABASE omop;
    GRANT ALL PRIVILEGES ON DATABASE synthea TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE omop TO $POSTGRES_USER;
EOSQL